-- AlterTable
ALTER TABLE `employee` MODIFY `createdAt` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `updatedAt` DATETIME(3) NULL,
    MODIFY `role` INTEGER NULL DEFAULT 0,
    MODIFY `address` VARCHAR(191) NULL;

-- AlterTable
ALTER TABLE `manager` MODIFY `createdAt` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `updatedAt` DATETIME(3) NULL,
    MODIFY `address` VARCHAR(191) NULL;
